[package]
name = "adf_test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.77"
